name: Check
on: [push, pull_request]
jobs:
  check:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - run: rustup toolchain install nightly --profile minimal --component rustfmt
      - shell: pwsh
        run: ./check-all.ps1
